/*
  Generates browser runtime config files (env.js) from environment variables.

  Why: `.env` is not readable by the browser, but `env.js` is.
  This script lets you keep a single source of truth (e.g. VITE_BACKEND_URL)
  and generate `window.ENV.BACKEND_URL` for the static HTML pages.

  Usage:
    node scripts/generate-env-js.cjs

  Env vars:
    - BACKEND_URL (preferred for static HTML)
    - VITE_BACKEND_URL (fallback; also used by the Vite/React build)
*/

const fs = require('fs');
const path = require('path');

function normaliseUrl(value) {
  if (!value) return '';
  return String(value).trim().replace(/\/+$/, '');
}

const backendUrl = normaliseUrl(process.env.BACKEND_URL || process.env.VITE_BACKEND_URL);

const out = `window.ENV = window.ENV || {};
// Generated by scripts/generate-env-js.cjs
// Do NOT put secrets in this file (it is served to browsers).
window.ENV.BACKEND_URL = ${JSON.stringify(backendUrl)};
`;

const repoRoot = path.resolve(__dirname, '..');
const targets = [
  path.join(repoRoot, 'env.js'),
  path.join(repoRoot, 'public', 'env.js'),
  path.join(repoRoot, 'frontend', 'env.js'),
  path.join(repoRoot, 'frontend', 'public', 'env.js'),
];

for (const filePath of targets) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, out, 'utf8');
}

process.stdout.write(
  `Generated env.js with BACKEND_URL=${backendUrl || '(empty)'}\n` +
  targets.map((p) => `- ${path.relative(repoRoot, p)}`).join('\n') +
  '\n'
);
